name: preparely
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  google_fonts: ^4.0.3
  device_preview: ^1.1.0
  flutter_svg: ^0.22.0
  http: ^0.13.5
  get: ^4.6.5
  shared_preferences: ^2.0.17
  cached_network_image: ^3.2.1
  lottie: ^2.2.0
  vibration: ^1.7.4
  youtube_player_flutter: ^8.1.2
  syncfusion_flutter_pdfviewer: ^20.4.53
  path_provider: ^2.0.13
  intl: ^0.19.0
  vimeo_video_player: ^0.0.14
  pin_code_fields: ^7.3.0  # Add a specific version
  carousel_slider: ^4.1.1
  marquee: ^2.0.3
  shimmer: ^2.0.0
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logos/
    - assets/appBackgroundImage/
    - assets/drawerImages/
    - animations/
    - assets/lottie/wellDone.json
    - assets/lottie/ohNo.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/quick.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: quick_bold
      fonts:
        - asset: assets/fonts/quick_bold.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700

    - family: quick_semi
      fonts:
        - asset: assets/fonts/quick_semi.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
